version: '3'
services:
    web:
        build: .
        command: python app.py
        depends_on:
            - db
        volumes:
            - ./app:/usr/src/app
        ports:
            - '5000:5000'
        environment:
            DATABASE_URL: postgres://db@db/db
    db:
        image: postgres:9.6.2-alpine
        environment:
            POSTGRES_USER: db
            POSTGRES_PASSWORD: pw
            POSTGRES_DB: db
